# Generated by Django 2.0.4 on 2018-05-21 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='conversation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100)),
                ('response', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('gpio', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='door',
            fields=[
                ('device_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='RoomPi.device')),
                ('oncommand', models.CharField(max_length=100)),
                ('offcommand', models.CharField(max_length=100)),
            ],
            bases=('RoomPi.device',),
        ),
        migrations.CreateModel(
            name='fan',
            fields=[
                ('device_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='RoomPi.device')),
                ('oncommand', models.CharField(max_length=100)),
                ('offcommand', models.CharField(max_length=100)),
            ],
            bases=('RoomPi.device',),
        ),
        migrations.CreateModel(
            name='light',
            fields=[
                ('device_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='RoomPi.device')),
                ('oncommand', models.CharField(max_length=100)),
                ('offcommand', models.CharField(max_length=100)),
            ],
            bases=('RoomPi.device',),
        ),
    ]
