# Generated by Django 2.0.4 on 2018-05-23 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoomPi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='enable',
            field=models.BooleanField(default=False),
        ),
    ]
