# Generated by Django 2.0.4 on 2018-05-23 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoomPi', '0002_device_enable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='enable',
            field=models.CharField(default='0', max_length=1),
        ),
    ]
