# Generated by Django 2.0.4 on 2018-05-24 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoomPi', '0003_auto_20180523_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='state',
            field=models.BooleanField(default=False),
        ),
    ]
