# Generated by Django 2.0.4 on 2018-05-25 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoomPi', '0004_device_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='alarm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('gpio', models.CharField(max_length=2)),
                ('email', models.CharField(max_length=45)),
                ('phone', models.CharField(max_length=20)),
                ('enable', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='conversation',
        ),
        migrations.RemoveField(
            model_name='device',
            name='state',
        ),
    ]
