# Generated by Django 2.0.4 on 2018-05-25 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoomPi', '0005_auto_20180525_0157'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarm',
            name='buzzer',
            field=models.CharField(default='11', max_length=2),
        ),
    ]
